sources:
  - name: ipsum
    type: url
    path: https://antifilter.download/list/ipsum.lst

  - name: local_list
    type: file
    path: /opt/blacklist3/local.txt

md5_file: /etc/bird/md5sums.json
output_dir: /etc/bird

daemon:
  enabled: false
  interval_seconds: 3000

http:
  timeout_seconds: 10