sources:
  - name: ipsum
    type: url
    path: https://antifilter.download/list/ipsum.lst

  - name: subnet
    type: url
    path: https://antifilter.download/list/subnet.lst

  - name: ip-agr
    type: url
    path: https://github.com/ipverse/rir-ip/raw/refs/heads/master/country/ru/ipv4-aggregated.txt

  - name: digitalocean
    type: url
    path: https://raw.githubusercontent.com/itdoginfo/allow-domains/refs/heads/main/Subnets/IPv4/digitalocean.lst

  - name: Meta.lst
    type: url
    path: https://raw.githubusercontent.com/itdoginfo/allow-domains/refs/heads/main/Subnets/IPv4/Meta.lst

  - name: cloudflare
    type: url
    path: https://raw.githubusercontent.com/itdoginfo/allow-domains/refs/heads/main/Subnets/IPv4/cloudflare.lst

  - name: Microsoft
    type: url
    path: https://raw.githubusercontent.com/lord-alfred/ipranges/main/microsoft/ipv4.txt

  - name: Google.lst
    type: url
    path: https://raw.githubusercontent.com/lord-alfred/ipranges/main/google/ipv4.txt

  - name: local_list
    type: file
    path: ./local.txt

md5_file: md5sums.json
output_dir: output

daemon:
  enabled: false
  interval_seconds: 300
